server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true # 强制强制强制，重要的事情说三遍
      force-request: true
      force-response: true
        # 核心：启用转发头自动识别
      forward-headers-strategy: native
      tomcat:
        remoteip:
          internal-proxies: .*    # 信任所有代理（仅调试用）
spring:
  application:
    name: sky-take-out-AI
  config:
    import: classpath:secrets.yaml

  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 5000ms  # 加上连接超时
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 3000ms
      shutdown-timeout: 100ms

  ai:
    openai:
      chat:
        base-url: https://api.deepseek.com
        # api-key 见 secrets.yaml
        options:
          model: deepseek-v4-flash
          extra-body:
            thinking:
              type: disabled
      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        # api-key 见 secrets.yaml
        options:
          model: text-embedding-v4  #向量模型
          dimensions: 1024   #向量维数

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    # password 见 secrets.yaml


# SpringDoc OpenAPI（生成 API 文档）与 Knife4j（增强 Swagger UI 界面）
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.kanodays88.kanodays88aiagent.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug  #为springai下的环绕增强开启日志
    com.kanodays88.ai: debug  #为该包下的类开启日志

# app.baidu.api.key 见 secrets.yaml
